---
title: "README"
author: "Jostein Barry-Straume"
date: "6/20/2017"
output: html_document
---

# Live Session unit 06 Assignment

> (Units 5 and 6)
> Creating projects in RStudio

## The live session assignment is due on Tuesday, June 22. 

> Here is the assignment:

* Using the Rolling Data Sales website, download and examine another housing sales data set (not the one we will use in live session, which is linked here - [Rolling Housing Sales for NYC](http://www1.nyc.gov/home/search/index.page?search-terms=Rolling+sales+update))

([http://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page](http://www1.nyc.gov/site/finance/taxes/property-rolling-sales-data.page))

* Goal: Create an RStudio project for the analysis of this data set. Your file structure within the project should include the following:
    + A README file in the project root directory that includes an explanation of the purpose of the project and the other files
    + A data directory containing files to load in and clean up the data. The clean up should include finding out where there are outliers or missing values, deciding how you will treat them, making sure values you think are numerical are being treated as such (correct R class), etc.
    + An Analysis directory containing a file (or files) for exploratory data analysis on the clean data to visualize compare the square footage and sales price for your neighborhood.
  
* Deliverable: A link to a repository on GitHub containing the above. I need only one link per group. Since this is a group project, I expect you to divide the labor.


